### ISSUE TITLE
⚠  Something went wrong!

### ISSUE THREAD

**Issue by RannyLike** [TheKliko/klikos-modding-tool#2]
SyntaxError: f-string: expecting '}' (mod_updater.py, line 42)

any way to solve this? its really difficult for me to use discord at the moment

**Comment by TheKliko** [comment]
What version of Python are you using? (open a command prompt and type "python -V")

I used python 3.12 when making this and I didn't really think about making it compatible with older python versions

**Comment by RannyLike** [comment]
ah its python 3.10.11, i shall try upgrading the version

**Comment by TheKliko** [comment]
I just released an update that adds a GUI and doesn't require python anymore because it's converted to a .exe using pyinstaller:
https://github.com/TheKliko/klikos-modding-tool/releases/tag/v1.3.0

I recommend using this version instead

**Comment by RannyLike** [comment]
quick question then where can i enable bloxstrap mode? I dont know where is the launch options

**Comment by TheKliko** [comment]
sorry for the late response,

it will show up in the menu if you have a compatible mod and if bloxstrap is installed in the default location (%localappdata%/Bloxstrap)

if your mod is compatible it should have an info.json file with this in it:
```
{
    "clientVersionUpload": "version-xxxxx"
}
```
(version-xxxxx being the roblox version that the mod was last updated for)
